### PR TITLE
Support pip via conda

### PR DESCRIPTION
**Pull request by mattgodbolt**
Adds beginnings of tests for installers too. Adds example of installing `conan` via pip.

### CODE REVIEW

**Comment by lhayhurst** [comment]
pip pip horray! thanks for the tests

**Review by lhayhurst — COMMENTED** [review]
pip pip horray! thanks for the tests

**Comment by lhayhurst** [comment]
I may have merged this too soon -- apologies if so :/

**Comment by mattgodbolt** [comment]
Haha :) you merged it before even approving it :grinning: -- it's all good, was hoping @benrady could chime in with thoughts too. Ben, any thoughts still appreciated!

**Comment by benrady** [comment]
Looks good. Nice to be able to install conan via ozy.

**Pull request merged**
